apiVersion: v1
kind: Pod
metadata:
  name: computeresourcepod3
  namespace: sit
  labels: 
    env: sit
spec:
  containers:
  - name: computeresource-cont3 
    image: nginx:latest
    ports:
    - containerPort: 90
    resources:
      requests:
        memory: 250Mi
        cpu: 0.4
      limits:
        memory: 250Mi
        cpu: 0.5 