apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: prod
spec:
  containers:
    - name: firstevercontainer
      image: nginx:latest
      resources:
       requests: 
         memory: "100Mi"
         cpu: "100m"
    #nodeSelector: 
      #nodetype: "production" 
    
    
