apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    label1: aws
    label2: docker
    label3: linux
spec:
    containers:
    - name: firstcontainer
      image: nginx:latest
      env:
      - name: myname
        value: arjun
      - name: city
        value: patiala 
      args: ["sleep", "3600"]  
    - name: secondcontainer
      image: nginx:latest   
    ports:
    - containerport: 80