
apiVersion: v1
kind: Pod
metadata:
  name: hello-worker
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
    hostnetwork: true 
  containers:
    - name: hello
      image: nginx
      ports:
        - containerPort: 80