apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80       # Port inside the cluster
      targetPort: 80 # Port in the container
      nodePort: 30007 # Port on your machine (can be between 30000–32767)
