apiVersion: v1
kind: Service
metadata:
  name: nginx-service-deploy
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
    nodePort: 31000 # default range 3000 - 32767

