apiVersion: v1
kind: Pod
metadata:
  name: storagepodhost
  namespace: sit
  labels:
    env: sit
    app: nginx
spec:
  containers:
  - name: container
    image: nginx:latest
    volumeMounts:
    - mountPath: /arjundata
      name: emptydirvolume
  volumes:
  - name: emptydirvolume
    emptyDir: {}