apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: nginx
  namespace: sit
spec:
  
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecretfile # this is cm already created from the local folder on node
     
  containers:
  - name: container1
    image: nginx:latest
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true 
  