apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: nginx
  namespace: sit
spec:
  
  volumes:
  - name: configmap-volume
    configMap:
      name: configmapfromyaml # this is cm already created from the local folder on node
     
  containers:
  - name: container1
    image: nginx:latest
    volumeMounts:
    - name: configmap-volume
      mountPath: /Arjundata
      readOnly: true 
  